[general]
allowUnstableNodeModules = true

[install]
[install.dedupe]
[install.globalDirectory]
[install.globalPrefix]
[install.production]
[install.registry]
[install.rollup]

[package]
[package.dependencies]
[package.devDependencies]
[package.peerDependencies]
[package.optionalDependencies]
[package.bundledDependencies]
[package.engines]
[package.os]
[package.cpu]
[package.main]
[package.browser]
[package.module]
[package.exports]
[package.bin]
[package.man]
[package.directories]
[package.type]
[package.types]
[package.typesVersions]
[package.files]
[package.sideEffects]

[scripts]
[scripts.define]
