// Code generated by scripts/generate-contract.ts; DO NOT EDIT.
// Upload/MIME/metadata bounds: @sploot/common. Attempt ceilings: economics/policy.json.
// Model revision: apps/web/lib/embeddings.ts, retained during application cutover.
package contract

import "strings"

const (
	UploadMaxBytes                 = 10485760
	UploadTimeoutMS                = 10000
	EmbeddingDimension             = 768
	TagMaxNameLength               = 128
	TagMaxColorLength              = 32
	TagMaxPerUser                  = 10000
	TagMaxPerAsset                 = 256
	TagMaxRequestItems             = 256
	AssetIDMaxLength               = 128
	EmbeddingGlobalDailyAttempts   = 2272
	EmbeddingGlobalMonthlyAttempts = 68181
	EmbeddingUserDailyAttempts     = 39
	EmbeddingUserMonthlyAttempts   = 796
	EmbeddingModel                 = "krthr/clip-embeddings:1c0371070cb827ec3c7f2f28adcdde54b50dcd239aa6faea0bc98b174ef03fb4"
	EmbeddingVersion               = "krthr/clip-embeddings:1c0371070cb827ec3c7f2f28adcdde54b50dcd239aa6faea0bc98b174ef03fb4"
)

var AllowedMIMETypes = []string{"image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif", "video/mp4", "video/webm"}

func IsAllowedMIME(value string) bool {
	value, _, _ = strings.Cut(value, ";")
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif", "video/mp4", "video/webm":
		return true
	default:
		return false
	}
}
