// Code generated by scripts/generate-contract.ts; DO NOT EDIT.
// Upload/MIME/metadata bounds: @sploot/common.
// Model identity and dimensions: the bundled local inference package.
package contract

import (
	"github.com/misty-step/sploot/apps/server/internal/inference"
	"strings"
)

const (
	UploadMaxBytes     = 10485760
	UploadTimeoutMS    = 10000
	TagMaxNameLength   = 128
	TagMaxColorLength  = 32
	TagMaxPerUser      = 10000
	TagMaxPerAsset     = 256
	TagMaxRequestItems = 256
	AssetIDMaxLength   = 128
	EmbeddingDimension = inference.Dimension
	EmbeddingModel     = inference.ModelVersion
	EmbeddingVersion   = inference.ModelVersion
)

var AllowedMIMETypes = []string{"image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif", "video/mp4", "video/webm"}

func IsAllowedMIME(value string) bool {
	value, _, _ = strings.Cut(value, ";")
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "image/jpeg", "image/jpg", "image/png", "image/webp", "image/gif", "video/mp4", "video/webm":
		return true
	default:
		return false
	}
}
