import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { ASSET, EMBEDDING_DIMENSION, TAG, UPLOAD } from '@sploot/common';
import ts from 'typescript';

const root = new URL('../../../', import.meta.url);
const destination = new URL('../internal/contract/generated.go', import.meta.url);
const sourcePath = new URL('apps/web/lib/embeddings.ts', root);
const source = ts.createSourceFile(fileURLToPath(sourcePath), await readFile(sourcePath, 'utf8'), ts.ScriptTarget.Latest, true);
let modelRevision: string | undefined;
for (const statement of source.statements) {
  if (!ts.isVariableStatement(statement)) continue;
  for (const declaration of statement.declarationList.declarations) {
    if (ts.isIdentifier(declaration.name) && declaration.name.text === 'CLIP_MODEL' && declaration.initializer && ts.isStringLiteral(declaration.initializer)) {
      modelRevision = declaration.initializer.text;
    }
  }
}
if (!modelRevision?.includes(':')) throw new Error('CLIP_MODEL must remain an explicit pinned model revision');
const policy = JSON.parse(await readFile(new URL('economics/policy.json', root), 'utf8'));
const constants = {
  UploadMaxBytes: UPLOAD.maxSize,
  UploadTimeoutMS: UPLOAD.timeout,
  EmbeddingDimension: EMBEDDING_DIMENSION,
  TagMaxNameLength: TAG.maxNameLength,
  TagMaxColorLength: TAG.maxColorLength,
  TagMaxPerUser: TAG.maxPerUser,
  TagMaxPerAsset: TAG.maxPerAsset,
  TagMaxRequestItems: TAG.maxRequestItems,
  AssetIDMaxLength: ASSET.maxIdLength,
  EmbeddingGlobalDailyAttempts: policy.global.replicateDailyAttempts,
  EmbeddingGlobalMonthlyAttempts: policy.global.replicateMonthlyAttempts,
  EmbeddingUserDailyAttempts: policy.planBudgets.free.dailyInferenceAttempts,
  EmbeddingUserMonthlyAttempts: policy.planBudgets.free.monthlyInferenceAttempts,
};
for (const [name, value] of Object.entries(constants)) {
  if (!Number.isSafeInteger(value) || value <= 0) throw new Error(`${name} must be a positive safe integer`);
}
const go = `// Code generated by scripts/generate-contract.ts; DO NOT EDIT.
// Upload/MIME/metadata bounds: @sploot/common. Attempt ceilings: economics/policy.json.
// Model revision: apps/web/lib/embeddings.ts, retained during application cutover.
package contract

import "strings"

const (
${Object.entries(constants).map(([name, value]) => `\t${name} = ${value}`).join('\n')}
\tEmbeddingModel = ${JSON.stringify(modelRevision)}
\tEmbeddingVersion = ${JSON.stringify(modelRevision)}
)

var AllowedMIMETypes = []string{${UPLOAD.allowedTypes.map(value => JSON.stringify(value)).join(', ')}}

func IsAllowedMIME(value string) bool {
\tvalue, _, _ = strings.Cut(value, ";")
\tswitch strings.ToLower(strings.TrimSpace(value)) {
\tcase ${UPLOAD.allowedTypes.map(value => JSON.stringify(value)).join(', ')}:
\t\treturn true
\tdefault:
\t\treturn false
\t}
}
`;
const formatted = spawnSync('gofmt', [], { input: go, encoding: 'utf8' });
if (formatted.status !== 0) throw new Error(`gofmt failed: ${formatted.stderr}`);
const vendorSource = new URL('../node_modules/htmx.org/dist/htmx.min.js', import.meta.url);
const vendorDestination = new URL('../internal/web/static/vendor/htmx.min.js', import.meta.url);
const vendorLicenseSource = new URL('../node_modules/htmx.org/LICENSE', import.meta.url);
const vendorLicenseDestination = new URL('../internal/web/static/vendor/htmx.LICENSE', import.meta.url);
const outputs = [
  [destination, formatted.stdout],
  [vendorDestination, await readFile(vendorSource, 'utf8')],
  [vendorLicenseDestination, await readFile(vendorLicenseSource, 'utf8')],
  ...await Promise.all([192, 512].map(async size => [
    new URL(`../internal/web/static/icon-${size}.png`, import.meta.url),
    await readFile(new URL(`apps/web/public/icons/icon-${size}x${size}.png`, root)),
  ] as const)),
] as const;
for (const [path, content] of outputs) {
  if (process.argv.includes('--check')) {
    const expected = typeof content === 'string' ? Buffer.from(content) : content;
    if (!(await readFile(path).catch(() => Buffer.alloc(0))).equals(expected)) {
      throw new Error(`Generated contract or pinned HTMX asset is stale: ${fileURLToPath(path)}; run pnpm --filter server generate`);
    }
  } else {
    await mkdir(new URL('./', path), { recursive: true });
    await writeFile(path, content);
  }
}
console.log(process.argv.includes('--check') ? 'Shared contracts and pinned HTMX assets match their sources.' : 'Generated shared Go contracts and pinned HTMX assets.');
